// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Oth1tWvxszLP-7Qlq8VZJOkFyeqWurI',
    appId: '1:924575698244:web:4f9dda7f0b1f4179649b11',
    messagingSenderId: '924575698244',
    projectId: 'smart-attendance-7b79f',
    authDomain: 'smart-attendance-7b79f.firebaseapp.com',
    storageBucket: 'smart-attendance-7b79f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOlncnZmhPK5QSQoV1D7eKJsKlXDOyL4E',
    appId: '1:924575698244:android:cd75388e3fe5cfc8649b11',
    messagingSenderId: '924575698244',
    projectId: 'smart-attendance-7b79f',
    storageBucket: 'smart-attendance-7b79f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4tHMFBvNR571JP2Q_kKhX4ygdY2MYWk',
    appId: '1:924575698244:ios:38cfc5d59f25de3f649b11',
    messagingSenderId: '924575698244',
    projectId: 'smart-attendance-7b79f',
    storageBucket: 'smart-attendance-7b79f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG4tHMFBvNR571JP2Q_kKhX4ygdY2MYWk',
    appId: '1:924575698244:ios:38cfc5d59f25de3f649b11',
    messagingSenderId: '924575698244',
    projectId: 'smart-attendance-7b79f',
    storageBucket: 'smart-attendance-7b79f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
